### ISSUE TITLE
Variable sliders not showing working in Photoshop on Windows?

### ISSUE THREAD

**Issue by tnboman** [arrowtype/shantell-sans#128]
Hey Stephen! My editor tried to create some mockups in Photoshop but couldn't get the variable axes sliders to work in Photoshop (v25.1) on Windows 10 (22H2). Seems to work fine in Illustrator. Working fine for me on the Mac in all Adobe apps. An odd bug!

**Comment by arrowtype** [comment]
Shoot! Thanks for reporting. That sounds like a Photoshop bug, from what I can tell, but it's good to document here in case others experience the same thing.

Are you able to make the mockups in another app?

**Comment by tnboman** [comment]
Appears to be Photoshop specific, but he did say he tested some other variable fonts and they were working correctly in Psd, just not Shantell Sans. I'll ask him to give me more details or stop being lazy and create a github account himself! 😅 Hopefully it'll be fixed in a future update from Adobe. We can close this ticket when it is. Thanks Stephen!

**Comment by arrowtype** [comment]
Thanks for taking time to file the issue. To be honest, Adobe has quite a few bugs with handling variable fonts, and Shantell Sans is a bit of an oddball font, so it isn’t super surprising that it might hit some kind of edge case in Photoshop. But, because Shantell Sans is working elsewhere, that does seem to indicate that the problem lies with Photoshop. 

If you would like to file the bug with Adobe, it seems that [they recommend](https://community.adobe.com/t5/photoshop-ecosystem-bugs/how-do-i-write-a-bug-report/idi-p/12373403) filing Photoshop bugs [in this part of the Adobe community](https://community.adobe.com/t5/forums/searchpage/tab/message?filter=location&q=P:&noSynonym=false&location=idea-board:bug-photoshop&sort_by=-topicPostDate&collapse_discussion=true).

I’ll close the issue here, but it’s good to have in the archive case others have the same problem and want to share any additional info. If you or your video editor do file a bug with Adobe, please also link that here. 

Thanks again!
